version: "3.8"
services:
  api-service:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api-container
    ports: 
      - '5000:5000'
    volumes:
      - ./api:/app
      - /app/node_modules
  www-service:
    build:
      context: ./www
      dockerfile: ./Dockerfile
    container_name: www-container
    ports:
      - '3000:3000'
    stdin_open: true
    volumes:
      - ./www:/app
      - /app/node_modules
  reverse-proxy-service:
    image: nginx:stable-alpine
    container_name: reverse-proxy-container
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8081:81"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf