version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports: 
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  wwww:
    build: ./www
    container_name: www_c
    ports:
      - '8080:8080'
    volumes:
      - ./www:/app
      - /app/node_modules